spring:
  rabbitmq:
    host: 192.168.45.131
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: auto

services:
  image:
    ocr:
      exchange: image.response
      queue: image.ocr.response.queue
      routing-key: image.ocr.response
    validation:
      exchange: image.response
      queue: image.validation.response.queue
      routing-key: image.validation.response
    thumbnail:
      exchange: image.response
      queue: image.thumbnail.response.queue
      routing-key: image.thumbnail.response
