spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./ggomgdb;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
        show_sql: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console
